package com.provys.wikiloader.impl;

import com.provys.provyswiki.ProvysWikiClient;

import javax.annotation.Nonnull;
import java.util.Collection;

/**
 * Object handler represents object in Enterprise Architect and can export it as wiki page. Specific implementations
 * can be made for individual object types (elements, packages, etc.)
 */
public interface Handler {

    /**
     * @return link to element, relative from enclosing package / element
     */
    @Nonnull
    String getRelLink();

    /**
     * Append all topics and namespaces generated by this element to parent's namespace
     *
     * @param pages is collection of pages, where this handler's generated topics and namespaces should be added to
     */
    void appendPages(Collection<String> pages);

    /**
     * Synchronize wiki page, corresponding to given element
     *
     * @param wikiClient is wikipedia client, used for export
     * @param recursive defines if we should export even sub-packages and elements or only given object and associated
     *                 diagrams
     */
    void sync(ProvysWikiClient wikiClient, boolean recursive);
}
